### ISSUE TITLE
Enable GitHub pages https://vlukashov.github.io/layout-lab/

### ISSUE THREAD

**Issue by limonte** [vlukashov/layout-lab#1]
It will be really nice to have a quick link https://vlukashov.github.io/layout-lab/ in the repo description.

Here's the guide how to make it in couple of clicks: https://github.com/blog/2228-simpler-github-pages-publishing

---

This will probably require using 3rd-party libraries via CDN and ret rid of bower

**Comment by vlukashov** [comment]
Done.
